[launchers.matrix]
binary = "/usr/bin/cmatrix"
pane = "bottom"
lolcat = "never"
persist = false

[launchers.say]
binary = "/usr/games/cowsay"
pane = "companion"
lolcat = "never"
persist = true

[launchers.letters]
binary = "/usr/bin/figlet"
pane = "bottom"
lolcat = "never"
persist = true

[launchers.sl]
binary = "/usr/games/sl"
pane = "bottom"
lolcat = { chance = 0.25 }
persist = false

[launchers.nyan]
binary = "/usr/bin/nyancat"
pane = "bottom"
lolcat = "never"
persist = false

[launchers.ll]
binary = "/bin/ls -la"
pane = "none"
lolcat = "never"
persist = false
builtin = true

[launchers.help]
binary = "{KID} help"
pane = "popup"
lolcat = "never"
persist = false
builtin = true

[launchers.man]
binary = "/usr/bin/man"
pane = "popup"
lolcat = "never"
persist = true

[launchers.tuxpaint]
category = "art"
binary = "tuxpaint"
pane = "none"
lolcat = "never"
persist = false
gui = true

[systems.apple2gs]
template = "mame apple2gs -rompath {rom_dir} -skip_gameinfo -nowindow -flop3 {rom_path}"
rom_dir = "/kid/emulation/disks/apple2gs"

[systems.snes]
template = "retroarch -L /usr/lib/*/libretro/bsnes_mercury_performance_libretro.so --config {home}/.config/retroarch/retroarch.cfg {rom_path}"
rom_dir = "/kid/emulation/disks/snes"

[systems.snes-mouse]
template = "retroarch -L /usr/lib/*/libretro/bsnes_mercury_performance_libretro.so -d 1:2 --config {home}/.config/retroarch/retroarch.cfg --appendconfig {home}/.config/retroarch/mouse.cfg {rom_path}"
rom_dir = "/kid/emulation/disks/snes"

[systems.scummvm]
template = "scummvm -f --path={rom_path} --auto-detect"
rom_dir = "/kid/emulation/disks/scummvm"

[systems.dosbox]
template = "dosbox -fullscreen -exit -c \"imgmount d {rom_path} -t iso\" -c \"d:\""
rom_dir = "/kid/emulation/disks/dosbox"

[systems.dosbox-carmen]
template = "dosbox -fullscreen -exit -c \"imgmount d {rom_path} -t iso\" -c \"d:\" -c \"carmen.exe\""
rom_dir = "/kid/emulation/disks/dosbox"

[systems.dosbox-donald]
template = "dosbox -fullscreen -exit -c \"mount c {rom_path}\" -c \"c:\" -c \"donald.exe\""
rom_dir = "/kid/emulation/disks/dosbox"

[games.nummunch]
category = "math"
system = "apple2gs"
rom = "num_munchers.woz"

[games.wordmunch]
category = "abc"
system = "apple2gs"
rom = "word_munchers.woz"

[games.fracmunch]
category = "math"
system = "apple2gs"
rom = "fraction_munchers.woz"

[games.donald]
category = "abc"
system = "dosbox-donald"
rom = "donald"

[games.oregon]
category = "trail"
system = "apple2gs"
rom = "oregon.woz"

[games.odell]
category = "play"
system = "apple2gs"
rom = "odell.woz"

[games.murphy]
category = "play"
system = "apple2gs"
rom = "murphys_minerals.woz"

[games.mario]
category = "art"
system = "snes-mouse"
rom = "mario_paint.sfc"

[games.parade]
category = "putt"
system = "scummvm"
rom = "putt_parade"

[games.moon]
category = "putt"
system = "scummvm"
rom = "putt_moon"

[games.zoo]
category = "putt"
system = "scummvm"
rom = "putt_zoo"

[games.amazon]
category = "trail"
system = "dosbox"
rom = "amazon_trail.iso"

[games.yukon]
category = "trail"
system = "dosbox"
rom = "yukon_trail.iso"

[games.carmen]
category = "play"
system = "dosbox-carmen"
rom = "carmen.iso"

[launchers.gcompris]
category = "abc"
binary = "gcompris-qt"
pane = "none"
lolcat = "never"
persist = false
gui = true

[launchers.scratch]
category = "code"
binary = "scratch"
pane = "none"
lolcat = "never"
persist = false
gui = true
enabled = true

[launchers.tuxmath]
category = "math"
binary = "tuxmath"
pane = "none"
lolcat = "never"
persist = false
gui = true

[launchers.tuxtype]
category = "abc"
binary = "tuxtype"
pane = "none"
lolcat = "never"
persist = false
gui = true

[launchers.klettres]
category = "abc"
binary = "klettres"
pane = "none"
lolcat = "never"
persist = false
gui = true

[launchers.krita]
category = "art"
binary = "krita"
pane = "none"
lolcat = "never"
persist = false
gui = true


[passthroughs]
ls    = "/bin/ls"
cat   = "/usr/bin/cat"
less  = "/usr/bin/less"
file  = "/usr/bin/file"
touch = "/usr/bin/touch"
echo  = "/usr/bin/echo"
whoami = "/usr/bin/whoami"
date  = "/usr/bin/date"
tmux  = "/usr/bin/tmux"
reset = "/usr/bin/reset"
bash  = "/usr/bin/bash"
base64 = "/usr/bin/base64"
iconv = "/usr/bin/iconv"
mkdir = "/bin/mkdir"
rmdir = "/bin/rmdir"
pwd   = "/bin/pwd"
wc    = "/usr/bin/wc"
head  = "/usr/bin/head"
tail  = "/usr/bin/tail"
grep  = "/bin/grep"
cal   = "/usr/bin/cal"
nano  = "/usr/bin/nano"
rm    = "/bin/rm"
mv    = "/bin/mv"
cp    = "/bin/cp"
sl    = "/usr/games/sl"
uv    = "/usr/local/bin/uv"

[blocks]
commands = ["sudo", "ssh", "curl", "wget", "su", "scp", "sftp", "wall"]
message = "{cmd} is not allowed... you are not going to get to use this one for a while."
