services:
  kid-host-sim:
    container_name: kid-host-sim
    build:
      context: ../..
      dockerfile: Dockerfile
    volumes:
      - ../..:/opt/kid-cli
      - kid-sim-data:/var/lib/kid-cli
    environment:
      - SIMULATOR=true
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "5900:5900"
    command: sleep infinity

volumes:
  kid-sim-data:
